---
- hosts: south
  vars_files: vault/local.yml
  roles:
    - ansible-role-get-manifest
    - ansible-role-create-vm
    - ansible-role-join-domain
    
- hosts: south
  vars_files: vault/domain.yml
  roles:
    - ansible-role-oracle
    - ansible-role-pre-deploy
    - ansible-role-deploy-db
